## Numpy Library Exercises

In [2]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [3]:
arr = np.random.randint(0, 15, 10)
print("Before:", arr)
arr = np.where((arr >= 3) & (arr <= 8), -arr, arr)
print("After:", arr)

Before: [10 14  9 13  6 13  0  6 14  1]
After: [10 14  9 13 -6 13  0 -6 14  1]


**2.** Replace the maximum element of a random array with 0

In [6]:
print("Before:", arr)
arr[np.argmax(arr)] = 0
print("After:", arr)

Before: [10  0  9 13 -6 13  0 -6 14  1]
After: [10  0  9 13 -6 13  0 -6  0  1]


**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [8]:
# "Direct product"/"декартово произведение" - комбинация всех со всеми, не арифметика
def cartesian_product_v2(arrays):
    grids = np.meshgrid(*arrays, indexing='ij')
    return np.stack(grids, axis=-1).reshape(-1, len(arrays))

result = cartesian_product_v2([[1, 2, 3], [4, 5]])
print(result)

[[1 4]
 [1 5]
 [2 4]
 [2 5]
 [3 4]
 [3 5]]


**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [9]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

print("A:\n", A)
print("B:\n", B)

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]

print("Индексы подходящих строк:", rows)

A:
 [[0 4 3]
 [3 2 1]
 [3 2 3]
 [0 2 1]
 [2 4 4]
 [4 2 0]
 [3 1 1]
 [0 4 2]]
B:
 [[3 2]
 [2 3]]
Индексы подходящих строк: [0 1 2 3 4 5 6 7]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [15]:
Z = np.random.randint(0, 2, (10, 3))
print("До:\n", Z)

# Сравниваем каждый элемент строки с первым элементом этой же строки
E = np.all(Z == Z[:, 0:1], axis=1)

# Оставляем только те строки, где НЕ все элементы равны (инвертируем маску)
U = Z[~E]
print("После:\n", U)

До:
 [[0 0 0]
 [1 0 1]
 [1 0 0]
 [1 0 1]
 [1 0 0]
 [0 1 1]
 [1 1 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]]
После:
 [[1 0 1]
 [1 0 0]
 [1 0 1]
 [1 0 0]
 [0 1 1]
 [1 1 0]
 [0 0 1]]


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])
print("До:\n", A)

B = np.unique(A, axis=0)
print("После:\n", B)

До:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]
После:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [22]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
# диагональ: X[0,0]=1, X[1,1]=0, X[2,2]=3
# произведение ненулевых: 1 * 3 = 3

def diag_product_pure(X):
    n = min(len(X), len(X[0]))
    result = 1 #чтобы избежать умножения на 0
    for i in range(n):
        val = X[i][i]
        if val != 0:
            result *= val
    return result

print(diag_product_pure(X))


X_np = np.array(X)
def diag_product_np(X):
    d = np.diagonal(X)
    return d[d != 0].prod()

print(diag_product_np(X_np))  

3
3


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [23]:
#Вектор одномерный массив
#множество, в котором элементы могут повторяться

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
x_np = np.array(x)
y_np = np.array(y)

def same_multiset_pure(x, y):
    if len(x) != len(y):
        return False
    
    counts_x = {}
    for val in x:
        counts_x[val] = counts_x.get(val, 0) + 1
    
    counts_y = {}
    for val in y:
        counts_y[val] = counts_y.get(val, 0) + 1
    
    return counts_x == counts_y

print(same_multiset_pure(x, y))


def same_multiset_np(x, y):
    return np.array_equal(np.sort(x), np.sort(y))

print(same_multiset_np(x_np, y_np))


True
True


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [24]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
x_np = np.array(x)

def max_after_zero_pure(x):
    candidates = []
    for i in range(1, len(x)):
        if x[i - 1] == 0:
            candidates.append(x[i])
    return max(candidates)

print(max_after_zero_pure(x))

def max_after_zero_np(x):
    mask = x[:-1] == 0
    return x[1:][mask].max()

print(max_after_zero_np(x_np))


5
5


* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [25]:
x = [2, 2, 2, 3, 3, 3, 5]
x_np = np.array(x)

def rle_pure(x):
    values = []
    counts = []
    
    prev = x[0]
    count = 1
    
    for val in x[1:]:
        if val == prev:
            count += 1
        else:
            values.append(prev)
            counts.append(count)
            prev = val
            count = 1
    
    values.append(prev)
    counts.append(count)
    
    return values, counts

print(rle_pure(x))

def rle_np(x):
    change_points = np.where(x[1:] != x[:-1])[0] + 1
    idx = np.concatenate(([0], change_points, [len(x)]))
    
    values = x[idx[:-1]]
    counts = np.diff(idx)
    
    return values, counts

print(rle_np(x_np))

([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1]))


* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [34]:
# матрица евклидовой дистанции ...
# евклидова дистанция - число, которое отражает 
# "насколько два объекта похожи/непохожи" с учётом всех их признаков одновременно 
# а не просто сравнение по одному признаку за раз.
# distance(a, b) = √((a₁-b₁)² + (a₂-b₂)²)

X = [[0, 0], [1, 1], [2, 2]]
Y = [[0, 0], [3, 4], [1, 0]]

X_np = np.array(X)
Y_np = np.array(Y)

def euclidean_py(X, Y):
    n = len(X)
    m = len(Y)
    result = [[0] * m for _ in range(n)]
    
    for i in range(n):
        for j in range(m):
            s = 0
            for k in range(len(X[i])):
                s += (X[i][k] - Y[j][k]) ** 2
            result[i][j] = s ** 0.5
    
    return result

result_py = euclidean_py(X, Y)
rounded = [[round(val, 2) for val in row] for row in result_py]
print(rounded)


def euclidean_np(X, Y):
    diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
    return np.sqrt((diff ** 2).sum(axis=2))

result_np = euclidean_np(X_np, Y_np)
print(np.round(result_np, 2))

[[0.0, 5.0, 1.0], [1.41, 3.61, 1.0], [2.83, 2.24, 2.24]]
[[0.   5.   1.  ]
 [1.41 3.61 1.  ]
 [2.83 2.24 2.24]]


_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [35]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [36]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [39]:
crunchie_calories = 60

average_calories = calorie_stats.mean() - crunchie_calories
print(round(average_calories, 2))

46.88


3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [40]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [41]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [42]:
nth_percentile = np.percentile(calorie_stats, 4)
print(nth_percentile)

70.0


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [43]:
more_calories = (calorie_stats > 60).mean() * 100
print(more_calories)

96.1038961038961


7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [44]:
calorie_std = calorie_stats.std()
print(calorie_std)

19.35718533390827


8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [167]:
# Mathematically proves the advantage